./BinaryOps input1.txt
./BinaryOps input2.txt
./BinaryOps input3.txt
./BinaryOps input4.txt
./BinaryOps input5.txt
./BinaryOps input6.txt
./BinaryOps input7.txt
./BinaryOps input8.txt
./BinaryOps input9.txt
./BinaryOps input10.txt
